vulnerability_severity:
  critical: 4.0
  major: 3.0
  minor: 2.0
  general: 1.0
  none: 0.0

reward_weights:
  vulnerability: 0.5    
  depth: 0.25          
  diversity: 0.25      

depth_reward:
  base_multiplier: 0.1
  max_depth: 1000
  normalization: true


diversity_reward:
  cwe_categories: true
  protocol_coverage: true
  field_coverage: true


combinatorial_reward:
  enabled: true
  protocol_interaction: 0.1
  field_correlation: 0.05
  temporal_sequence: 0.05


exploration_reward:
  new_path_bonus: 2.0
  coverage_bonus: 1.5
  novelty_bonus: 1.0


penalties:
  invalid_message: -0.1
  repeated_coverage: -0.05
  timeout: -0.2