# EtherNet/IP protocol configuration
name: "ethernet_ip"
port: 44818
description: "EtherNet/IP Industrial Protocol"

# Protocol field definitions
fields:
  command:
    position: [0, 2]
    type: "uint16"
    description: "Command code"
    mutable: true
    default: 111
    state_dim: 16
    action_dim: 6
    
  length:
    position: [2, 4]
    type: "uint16"
    description: "Data length"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 6
    
  session_handle:
    position: [4, 8]
    type: "uint32"
    description: "Session handle"
    mutable: true
    default: 0
    state_dim: 32
    action_dim: 5
    
  status:
    position: [8, 12]
    type: "uint32"
    description: "Status code"
    mutable: true
    default: 0
    state_dim: 32
    action_dim: 5
    
  sender_context:
    position: [12, 20]
    type: "bytes"
    description: "Sender context"
    mutable: true
    default: "0000000000000000"
    state_dim: 64
    action_dim: 6
    
  options:
    position: [20, 24]
    type: "uint32"
    description: "Option flags"
    mutable: true
    default: 0
    state_dim: 32
    action_dim: 4
    
  data:
    position: [24, null]
    type: "bytes"
    description: "Data field"
    mutable: true
    default: ""
    state_dim: 512
    action_dim: 8

# Mutation strategy configuration
mutation_strategies:
  - name: "command_injection"
    description: "Command injection"
    enabled: true
    
  - name: "session_hijacking"
    description: "Session hijacking"
    enabled: true
    
  - name: "data_corruption"
    description: "Data corruption"
    enabled: true

# Test case generation configuration
test_generation:
  seed_messages:
    - "006f00000000000000000000000000000000000200000000b2000000"  # SendRRData
  mutation_count: 1000
  priority_fields: ["command", "length", "data"]

# Agent training configuration
training:
  learning_rate: 0.001
  batch_size: 32
  buffer_size: 10000