# Modbus TCP protocol configuration
name: "modbus_tcp"
port: 502
description: "Modbus TCP Industrial Protocol"

fields:
  transaction_id:
    position: [0, 2]
    type: "uint16"
    description: "Transaction identifier"
    mutable: true
    default: 1
    
  protocol_id:
    position: [2, 4]
    type: "uint16" 
    description: "Protocol identifier"
    mutable: false
    default: 0
    
  length:
    position: [4, 6]
    type: "uint16"
    description: "Length (following bytes)"
    mutable: true
    default: 6
    
  unit_id:
    position: [6, 7]
    type: "uint8"
    description: "Unit identifier"
    mutable: true
    default: 1
    
  function_code:
    position: [7, 8]
    type: "uint8"
    description: "Function code"
    mutable: true
    default: 3
    valid_values: [1, 2, 3, 4, 5, 6, 15, 16]
    
  data:
    position: [8, null]
    type: "bytes"
    description: "Data field"
    mutable: true
    default: ""

# Mutation strategy configuration
mutation_strategies:
  - name: "boundary_values"
    description: "Boundary value testing"
    enabled: true
    
  - name: "invalid_function_codes" 
    description: "Invalid function codes"
    enabled: true
    
  - name: "length_field_manipulation"
    description: "Length field manipulation"
    enabled: true

# Test case generation configuration
test_generation:
  seed_messages:
    - "00010000000601030000000A"  # Read Holding Registers
    - "000200000006010600000001"  # Write Single Register
  mutation_count: 1000
  priority_fields: ["function_code", "length"]