# Siemens S7 协议配置
name: "siemens_s7"
port: 102
description: "Siemens S7 Industrial Protocol"

# 协议字段定义
fields:
  rosctr:
    position: [0, 1]
    type: "uint8"
    description: "ROSCTR 类型"
    mutable: true
    default: 1
    state_dim: 8
    action_dim: 4
    
  reserved:
    position: [1, 2]
    type: "uint8"
    description: "保留字段"
    mutable: false
    default: 0
    state_dim: 8
    action_dim: 3
    
  protocol_data_unit_reference:
    position: [2, 4]
    type: "uint16"
    description: "PDU 引用"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 5
    
  parameter_length:
    position: [4, 6]
    type: "uint16"
    description: "参数长度"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 6
    
  data_length:
    position: [6, 8]
    type: "uint16"
    description: "数据长度"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 6
    
  data:
    position: [8, null]
    type: "bytes"
    description: "数据字段"
    mutable: true
    default: ""
    state_dim: 512
    action_dim: 8

# 变异策略配置
mutation_strategies:
  - name: "pdu_manipulation"
    description: "PDU 操纵"
    enabled: true
    
  - name: "length_exploitation"
    description: "长度利用"
    enabled: true
    
  - name: "data_integrity"
    description: "数据完整性破坏"
    enabled: true

# 测试用例生成配置
test_generation:
  seed_messages:
    - "1100010000000000"  # 连接请求
  mutation_count: 1000
  priority_fields: ["rosctr", "parameter_length", "data_length"]

# 智能体训练配置
training:
  learning_rate: 0.001
  batch_size: 32
  buffer_size: 10000