# Siemens S7 protocol configuration
name: "siemens_s7"
port: 102
description: "Siemens S7 Industrial Protocol"

# Protocol field definitions
fields:
  rosctr:
    position: [0, 1]
    type: "uint8"
    description: "ROSCTR type"
    mutable: true
    default: 1
    state_dim: 8
    action_dim: 4
    
  reserved:
    position: [1, 2]
    type: "uint8"
    description: "Reserved field"
    mutable: false
    default: 0
    state_dim: 8
    action_dim: 3
    
  protocol_data_unit_reference:
    position: [2, 4]
    type: "uint16"
    description: "PDU reference"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 5
    
  parameter_length:
    position: [4, 6]
    type: "uint16"
    description: "Parameter length"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 6
    
  data_length:
    position: [6, 8]
    type: "uint16"
    description: "Data length"
    mutable: true
    default: 0
    state_dim: 16
    action_dim: 6
    
  data:
    position: [8, null]
    type: "bytes"
    description: "Data field"
    mutable: true
    default: ""
    state_dim: 512
    action_dim: 8

# Mutation strategy configuration
mutation_strategies:
  - name: "pdu_manipulation"
    description: "PDU manipulation"
    enabled: true
    
  - name: "length_exploitation"
    description: "Length exploitation"
    enabled: true
    
  - name: "data_integrity"
    description: "Data integrity violation"
    enabled: true

# Test case generation configuration
test_generation:
  seed_messages:
    - "1100010000000000"  # Connection request
  mutation_count: 1000
  priority_fields: ["rosctr", "parameter_length", "data_length"]

# Agent training configuration
training:
  learning_rate: 0.001
  batch_size: 32
  buffer_size: 10000